name: Release AddOn

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        uses: BigWigsMods/packager@v2
        env:
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}
